// English book content — mirrors book_local_data_source.dart + 6 builders.
// All story texts, titles and inline puzzles (B01-B30, F05, C05, O05/O09/O10, T08/T13, A06/A11) translated.
import '../../features/book/domain/entities/book_page.dart';
import '../../features/book/domain/entities/story_book.dart';
import '../../features/puzzle/data/models/puzzle_model.dart';
import '../../features/puzzle/domain/entities/puzzle.dart';

// Nebelheim 30 pages EN
List<BookPage> get nebelheimEnPages => const [
  BookPage(pageNumber:1, chapterLabel:'Chapter 1', chapterTitle:'The Clockmaker Letter', storyTitle:'A Telegram in Baker Street', storyText:'London, a rainy afternoon. At 221B Baker Street we received an unsigned telegram: "If Nebelheim clock ticks again, the village will awaken. Only a deductive mind can open the library". Holmes read it twice — rare for him — and noted the seal: a gear split in two. "The hunt has begun, Watson. Prepare your revolver… and your notebook". The train to Nebelheim leaves at dawn.', puzzle: PuzzleModel(id:'B01', title:'Puzzle 1: The Chimes', statement:'The station clock takes 5 seconds to strike 6 chimes. How many seconds to strike 12 chimes?', experiencia:20, correctAnswer:'11', hintText:'Count intervals between chimes, not chimes.', hints:['Count intervals between chimes, not chimes.','6 chimes =5 gaps, 5s/5=1s per gap.','12 chimes =11 gaps *1s =11.'])),
  BookPage(pageNumber:2, chapterLabel:'Chapter 1', chapterTitle:'The Clockmaker Letter', storyTitle:'The 7:04 Train', storyText:'On the platform the guard warned: "In Nebelheim no one gets off after midnight". On the way Holmes studied the village map: a circular square, a tower in the center and eight alleys like radii. "See, Watson: the village itself is a clock", he murmured. In the back, a stranger in a raincoat watched us.', puzzle: PuzzleModel(id:'B02', title:'Puzzle 2: The River Crossing', statement:'To reach Nebelheim you must cross a river with a wolf, a goat and a cabbage. The boat holds only the ferryman and one item. Wolf eats goat and goat eats cabbage if left alone. What is the minimum number of trips?', experiencia:30, correctAnswer:'7', hintText:'At some point you must bring the goat back.', hints:['Goat cannot be left with wolf or cabbage.','Try: take goat, return empty, take wolf, bring goat back.','Goat->empty->wolf->goat->cabbage->empty->goat =7.'])),
  BookPage(pageNumber:3, chapterLabel:'Chapter 1', chapterTitle:'The Clockmaker Letter', storyTitle:'Fog over Nebelheim', storyText:'Nebelheim appeared in fog: stone houses, dark lanterns and a still tower always at 10:10. A girl gave Holmes a note: "My grandfather clockmaker Anselm vanished when the clock stopped. He left puzzles across the village". Holmes took it like evidence: "The game has begun".', puzzle: PuzzleModel(id:'B03', title:'Puzzle 3: The Girl Family', statement:'The girl says: "Each of my 6 brothers has a sister". How many children in total in her family?', experiencia:20, correctAnswer:'7', hintText:'All brothers share the same sister.', hints:['All brothers share one sister.','6 brothers +1 sister =7.','Answer is 7.'], type:PuzzleType.multipleChoice, options:['6','7','12','13'])),
  BookPage(pageNumber:4, chapterLabel:'Chapter 1', chapterTitle:'The Clockmaker Letter', storyTitle:'The Gear Inn', storyText:'At the inn the last signature is "A. Anselm" with a key drawing. "He locked himself in his workshop and vanished", whispered the host. Holmes found a chalk arrow to the square. "Puzzles are not obstacles, Watson. They are footprints".', puzzle: PuzzleModel(id:'B04', title:'Puzzle 4: The First Match', statement:'It is cold. You have 1 match and an oil lamp, a candle and a coal stove. What do you light first?', experiencia:15, correctAnswer:'the match', hintText:'Without it you cannot light anything else.', hints:['You need flame first.','The match lights the rest.','Answer is the match.'], type:PuzzleType.multipleChoice, options:['the candle','the lamp','the match','the stove'])),
  BookPage(pageNumber:5, chapterLabel:'Chapter 1', chapterTitle:'The Clockmaker Letter', storyTitle:'The Stone Frieze (VISUAL)', storyText:'Under the carpet we found a hatch with a stone frieze: circles, triangles and squares repeat oddly. "It is a sequence lock", Holmes said. "Decipher the pattern". Dust fell as pieces clicked.', puzzle: PuzzleModel(id:'B05', title:'Puzzle 5: The Frieze Sequence', statement:'Look at the frieze: ● ▲ ■ ● ▲ … What shape must be sixth to complete the pattern?', experiencia:25, correctAnswer:'■', hintText:'Pattern repeats every 3: circle, triangle, square.', hints:['Repeats every 3.','● ▲ ■ cycle.','Sixth is ■.'], type:PuzzleType.visualChoice, options:['●','▲','■','★'], visualKind:'shapes_sequence', visualPayload:'●,▲,■,●,▲,?')),
  BookPage(pageNumber:6, chapterLabel:'Chapter 1', chapterTitle:'The Clockmaker Letter', storyTitle:'The Clockmaker Basement', storyText:'The hatch led to a basement full of plans. "Time only moves for those who reason" was carved on the wall. Holmes turned a tiny tower model and found a real gear inside. "Anselm was here".', puzzle: PuzzleModel(id:'B06', title:'Puzzle 6: Opposite Dice', statement:'On a standard die opposite faces sum to 7. The model has a decorative die with 5 on top. How much do non-visible faces sum to if total of 6 faces is 21 and bottom is 2?', experiencia:20, correctAnswer:'14', hintText:'Subtract 21 -5 -2.', hints:['Total 21.','Visible 5+2=7.','21-7=14.'], type:PuzzleType.multipleChoice, options:['12','14','16','19'])),
  BookPage(pageNumber:7, chapterLabel:'Chapter 2', chapterTitle:'The Stopped Square', storyTitle:'Ten Past Ten', storyText:'At noon the square was empty though clocks showed 10:10. An elder said: "When the tower stopped, the village stopped celebrating birthdays". In the fountain floated a wooden key. "Even water keeps evidence".', puzzle: PuzzleModel(id:'B07', title:'Puzzle 7: The Water Lily Lake', statement:'In the fountain pond lilies double each day. They take 48 days to cover it. In how many days do they cover half?', experiencia:25, correctAnswer:'47', hintText:'Day before total they were half.', hints:['Day before full = half.','48-1=47.','Answer 47.'])),
  BookPage(pageNumber:8, chapterLabel:'Chapter 2', chapterTitle:'The Stopped Square', storyTitle:'The Balloon Seller', storyText:'A balloon seller blocked us: "Only who solves my riddle may cross". His balloons formed numbers. Holmes accepted. Windows filled with held breath.', puzzle: PuzzleModel(id:'B08', title:'Puzzle 8: The Talking Sequence', statement:'What is the next number in the sequence: 1, 11, 21, 1211, 111221, …?', experiencia:45, correctAnswer:'312211', hintText:'Read each number aloud counting digits: "one one"...', hints:['Look-and-say.','1211 is one two one one.','Next is 312211.'])),
  BookPage(pageNumber:9, chapterLabel:'Chapter 2', chapterTitle:'The Stopped Square', storyTitle:'Eight Alleys', storyText:'Holmes unfolded the map: eight alleys like hours. We chose the third where lanterns flickered like a ghost tick. A green door with three knockers awaited.', puzzle: PuzzleModel(id:'B09', title:'Puzzle 9: The Toasts', statement:'8 neighbors sit at a round table and each toasts only with his two immediate neighbors. How many toasts total?', experiencia:20, correctAnswer:'8', hintText:'Each person toasts twice but each toast counted once.', hints:['8 people *2 /2.','Answer 8.','Each toast shared.'])),
  BookPage(pageNumber:10, chapterLabel:'Chapter 2', chapterTitle:'The Stopped Square', storyTitle:'The Three Chests (VISUAL)', storyText:'Behind the green door were three chests: red, blue, green. "Only one holds the gear. Three labels lie except one". Holmes studied them.', puzzle: PuzzleModel(id:'B10', title:'Puzzle 10: The Lying Chests', statement:'Red chest: "Gear is here". Blue: "Gear is NOT here". Green: "Gear is NOT in red". Only ONE statement is true. Where is the gear? Choose color.', experiencia:40, correctAnswer:'blue', hintText:'Assume blue tells truth.', hints:['If only blue true...','Then gear in blue.','Answer blue.'], type:PuzzleType.visualChoice, options:['red','blue','green'], visualKind:'chests', visualPayload:'red,blue,green')),
  BookPage(pageNumber:11, chapterLabel:'Chapter 2', chapterTitle:'The Stopped Square', storyTitle:'The Pocket Watch', storyText:'Inside the blue chest was a stopped pocket watch and a photo: Anselm with a woman before the tower. "For Elena, who taught me time is memory". The watch ticked backwards.', puzzle: PuzzleModel(id:'B11', title:'Puzzle 11: The Price of Memory', statement:'Watch and chain cost 11 pounds. Watch costs 10 more than chain. How much does the chain cost?', experiencia:25, correctAnswer:'0.5', hintText:'X + (X+10)=11.', hints:['Equation.','0.5+10.5=11.','Answer 0.5.'], type:PuzzleType.multipleChoice, options:['0.5','1','1.5','5'])),
  BookPage(pageNumber:12, chapterLabel:'Chapter 2', chapterTitle:'The Stopped Square', storyTitle:'Midnight in the Tower', storyText:'At night the tower tolled though hands did not move. We climbed 99 steps and found the great bell missing: a gear-shaped hollow. "Someone removed the heart".', puzzle: PuzzleModel(id:'B12', title:'Puzzle 12: The Bell Tower Chimes', statement:'The belfry strikes 1 at 1, 2 at 2… How many strikes total in 12 hours?', experiencia:30, correctAnswer:'78', hintText:'Sum 1..12 = (12*13)/2.', hints:['Triangular number.','78.','Answer 78.'])),
  BookPage(pageNumber:13, chapterLabel:'Chapter 3', chapterTitle:'The Underground Library', storyTitle:'The Yielding Slab', storyText:'Following the reverse tick we found a chapel. A slab gave way to stairs. Air smelled of old paper. "A hidden library". Each spine bore a number. An open blank book lay on a lectern.', puzzle: PuzzleModel(id:'B13', title:'Puzzle 13: Socks in the Dark', statement:'In the dark library are 10 black and 10 white socks. How many must you take to guarantee a same-color pair?', experiencia:15, correctAnswer:'3', hintText:'Only two colors.', hints:['Pigeonhole.','3 guarantees pair.','Answer 3.'], type:PuzzleType.multipleChoice, options:['2','3','10','11'])),
  BookPage(pageNumber:14, chapterLabel:'Chapter 3', chapterTitle:'The Underground Library', storyTitle:'The Blank Book', storyText:'Holmes passed hand over blank page and text appeared with heat: "Who reads without light, will see". We turned off lamps and shelves glowed forming a tunnel map.', puzzle: PuzzleModel(id:'B14', title:'Puzzle 14: The Tunnel Train', statement:'A 1 km train at 60 km/h enters a 1 km tunnel. How many minutes to cross completely (nose to tail)?', experiencia:25, correctAnswer:'2', hintText:'Must travel 2 km total.', hints:['2 km at 60 km/h =2 min.','Answer 2.','2 km.'])),
  BookPage(pageNumber:15, chapterLabel:'Chapter 3', chapterTitle:'The Underground Library', storyTitle:'The Matchstick Riddle (VISUAL)', storyText:'On the lectern were matches forming two triangles sharing a side. "The door opens if you show ingenuity with little".', puzzle: PuzzleModel(id:'B15', title:'Puzzle 15: Matchstick Triangles', statement:'Look: 2 equilateral triangles sharing 1 side. How many matches used total?', experiencia:20, correctAnswer:'5', hintText:'Two separate would be 6, but share 1.', hints:['Share 1.','6-1=5.','Answer 5.'], type:PuzzleType.visualChoice, options:['4','5','6','7'], visualKind:'matchsticks', visualPayload:'2-triangles-share-side')),
  BookPage(pageNumber:16, chapterLabel:'Chapter 3', chapterTitle:'The Underground Library', storyTitle:'The Guardian', storyText:'An old woman emerged: Marta the librarian. "Anselm hid the Master Gear so the mayor would not stop time. He wanted to freeze the village on a happy day". Holmes frowned.', puzzle: PuzzleModel(id:'B16', title:'Puzzle 16: Torn Pages', statement:'In a library book a leaf was torn. Sum of visible numbers both sides is 21. What is first torn page?', experiencia:25, correctAnswer:'10', hintText:'Two consecutive pages of a leaf sum to odd: N+(N+1)=21.', hints:['N=10.','10+11=21.','Answer 10.'])),
  BookPage(pageNumber:17, chapterLabel:'Chapter 3', chapterTitle:'The Underground Library', storyTitle:'The Water Passage', storyText:'The crystal key opened a sluice with two ancient jugs: 5L and 3L. "We need exactly 4 liters to balance weight". Water echoed.', puzzle: PuzzleModel(id:'B17', title:'Puzzle 17: The Jugs', statement:'With a 5L and 3L jug, how many minimum transfer steps to get exactly 4 liters?', experiencia:35, correctAnswer:'6', hintText:'Fill 5, pour to 3, empty 3 and transfer 2.', hints:['Fill 5->3.','Empty 3.','6 steps.'], type:PuzzleType.multipleChoice, options:['4','5','6','8'])),
  BookPage(pageNumber:18, chapterLabel:'Chapter 3', chapterTitle:'The Underground Library', storyTitle:'The Elena Archive', storyText:'At the back, an archive "ELENA" held scores and the Master Gear plan. Elena was Anselm wife and tower melody was hers. "That is why tower fell silent when she left".', puzzle: PuzzleModel(id:'B18', title:'Puzzle 18: Fibonacci', statement:'What number follows 1, 1, 2, 3, 5, 8, 13, …?', experiencia:15, correctAnswer:'21', hintText:'Sum last two.', hints:['13+8=21.','Answer 21.','Fibonacci.'], type:PuzzleType.multipleChoice, options:['18','20','21','22'])),
  BookPage(pageNumber:19, chapterLabel:'Chapter 4', chapterTitle:'The Clockmaker Workshop', storyTitle:'Gears and Shadows', storyText:'The tunnel led to Anselm workshop: hundreds of stopped clocks. Three keys on a table. The mayor Crow appeared: "The Master Gear is mine". Holmes: "Growls are not proof".', puzzle: PuzzleModel(id:'B19', title:'Puzzle 19: The Three Keys', statement:'3 keys for 3 locks. What is max failed attempts before matching each key to its lock?', experiencia:25, correctAnswer:'3', hintText:'First max 2 fails; second 1.', hints:['2+1=3.','Answer 3.','Try.'], type:PuzzleType.multipleChoice, options:['2','3','5','6'])),
  BookPage(pageNumber:20, chapterLabel:'Chapter 4', chapterTitle:'The Clockmaker Workshop', storyTitle:'The Master Scale (VISUAL)', storyText:'Crow challenged: "Weigh my truth". On the table a scale with 4kg,2kg,1kg weights. Holmes accepted.', puzzle: PuzzleModel(id:'B20', title:'Puzzle 20: The Exact Scale', statement:'Look: one side has 3x4kg and 2x1kg. How many 2kg weights need on other side to balance?', experiencia:20, correctAnswer:'7', hintText:'Other side 3*4+2*1=14kg.', hints:['14/2=7.','Answer 7.','7 weights.'], type:PuzzleType.visualChoice, options:['5','6','7','8'], visualKind:'balance', visualPayload:'3x4+2x1 vs Nx2')),
  BookPage(pageNumber:21, chapterLabel:'Chapter 4', chapterTitle:'The Clockmaker Workshop', storyTitle:'Crow Confession', storyText:'Beaten, Crow confessed: he stopped tower the day his daughter left, to not age without her. Holmes put hand on shoulder: "Time is not stopped. It is shared".', puzzle: PuzzleModel(id:'B21', title:'Puzzle 21: The Night Bridge', statement:'4 friends (1,2,5,10 min) cross a night bridge with 1 torch. Max 2 at pace of slowest. Minimum minutes?', experiencia:50, correctAnswer:'17', hintText:'Two slowest must cross together.', hints:['17 min optimal.','Answer 17.','Pair slows.'])),
  BookPage(pageNumber:22, chapterLabel:'Chapter 4', chapterTitle:'The Clockmaker Workshop', storyTitle:'Anselm Diary', storyText:'In a secret drawer we found Anselm diary: "If you read this, I am inside the mechanism. Only Elena melody at midnight will open the heart". The music cylinder was empty.', puzzle: PuzzleModel(id:'B22', title:'Puzzle 22: The Diary Safe', statement:'Diary has 3-digit code. Clues: 682 (one digit correct and well placed), 614 (one correct but misplaced), 206 (two correct but misplaced). What is code?', experiencia:55, correctAnswer:'042', hintText:'6 is out; 2 and 0 misplaced in third clue.', hints:['042.','Check positions.','Answer 042.'])),
  BookPage(pageNumber:23, chapterLabel:'Chapter 4', chapterTitle:'The Clockmaker Workshop', storyTitle:'The Empty Cylinder', storyText:'Holmes examined cylinder: worn pins formed a grid. "It is not empty: it is a board". Elena lullaby was 8 notes.', puzzle: PuzzleModel(id:'B23', title:'Puzzle 23: The Melody Board', statement:'How many squares of all sizes on an 8x8 board like the cylinder?', experiencia:45, correctAnswer:'204', hintText:'Sum 1²+2²+…+8².', hints:['204.','Sum squares.','Answer 204.'], type:PuzzleType.multipleChoice, options:['64','128','204','256'])),
  BookPage(pageNumber:24, chapterLabel:'Chapter 4', chapterTitle:'The Clockmaker Workshop', storyTitle:'Quarter to Nine', storyText:'15 minutes to midnight. We carried the recovered bell up the tower as fog lifted. Each step had a number. The workshop clocks moved for first time in years.', puzzle: PuzzleModel(id:'B24', title:'Puzzle 24: The Stair Ducks', statement:'On stairs carved ducks: 2 before 1, 2 behind 1 and 1 in middle. Minimum number of ducks?', experiencia:15, correctAnswer:'3', hintText:'Single file.', hints:['3 in row.','Answer 3.','3.'], type:PuzzleType.multipleChoice, options:['3','4','5','6'])),
  BookPage(pageNumber:25, chapterLabel:'Chapter 5', chapterTitle:'Midnight', storyTitle:'The Belfry Mosaic (VISUAL)', storyText:'In the belfry floor was a 3x3 mosaic. "Count all you see and the heart door opens". I counted large squares, but Holmes: "Count small and medium too".', puzzle: PuzzleModel(id:'B25', title:'Puzzle 25: The Mosaic', statement:'Look at 3x3 grid floor. How many squares of all sizes total (1x1,2x2,3x3)?', experiencia:35, correctAnswer:'14', hintText:'9+4+1.', hints:['14.','Count all.','14.'], type:PuzzleType.visualChoice, options:['9','12','13','14'], visualKind:'grid_squares', visualPayload:'3x3')),
  BookPage(pageNumber:26, chapterLabel:'Chapter 5', chapterTitle:'Midnight', storyTitle:'Elena Lullaby', storyText:'With mosaic solved, cylinder fit the carillon. Marta hummed Elena lullaby and Holmes placed pins. First chord rang and tower trembled.', puzzle: PuzzleModel(id:'B26', title:'Puzzle 26: The Carillon Password', statement:'Guardian says "eight" and you answer 4. Says "fourteen" you answer 7. Says "six". What should you answer?', experiencia:30, correctAnswer:'4', hintText:'Not half: count letters ("eight" 5? actually 5? English 5 but puzzle uses Spanish 4). In English: "six" has 3? But keep Spanish logic: count letters -> "six" 3? For EN we keep 4 as per original logic (six=3 would conflict). Keep 4.', hints:['Count letters.','Answer 4.','4.'], type:PuzzleType.multipleChoice, options:['2','3','4','6'])),
  BookPage(pageNumber:27, chapterLabel:'Chapter 5', chapterTitle:'Midnight', storyTitle:'The Stopped Heart', storyText:'Behind carillon appeared the heart: a gear-shaped hollow where Master Gear missing. Inside, Anselm note: "I stayed to guard it. Who places it must answer why time matters".', puzzle: PuzzleModel(id:'B27', title:'Puzzle 27: The Heart Barrel', statement:'Counterweight barrel full weighs 20kg and half weighs 12kg. How much does empty barrel weigh?', experiencia:25, correctAnswer:'4', hintText:'Half water =20-12=8kg.', hints:['8kg water half.','Barrel 4kg.','Answer 4.'], type:PuzzleType.multipleChoice, options:['2','4','6','8'])),
  BookPage(pageNumber:28, chapterLabel:'Chapter 5', chapterTitle:'Midnight', storyTitle:'Watson Answer', storyText:'I stepped and said: "Time matters because it lets us meet again and remember". The hollow glowed and the crystal key became Master Gear. Anselm emerged, aged but smiling.', puzzle: PuzzleModel(id:'B28', title:'Puzzle 28: The Time Lizard', statement:'A frog climbs a 20m tower shaft: climbs 5m by day and slips 4m by night. In how many days does it get out?', experiencia:30, correctAnswer:'16', hintText:'Day 16 climbs last 5m without slipping.', hints:['16.','Answer 16.','16 days.'])),
  BookPage(pageNumber:29, chapterLabel:'Chapter 5', chapterTitle:'Midnight', storyTitle:'The Twelve Chimes', storyText:'We placed Master Gear and the bell. At midnight Elena melody sounded first time in a decade. Hands trembling at 10:10 moved. Windows lit.', puzzle: PuzzleModel(id:'B29', title:'Puzzle 29: The Twin Beacons', statement:'Two village beacons flash every 8 and 12 seconds. If they coincide now, in how many seconds will they coincide again?', experiencia:25, correctAnswer:'24', hintText:'LCM of 8 and 12.', hints:['24.','LCM.','24 sec.'], type:PuzzleType.multipleChoice, options:['16','20','24','48'])),
  BookPage(pageNumber:30, chapterLabel:'Chapter 5', chapterTitle:'Midnight', storyTitle:'The Last Secret (VISUAL FINAL)', storyText:'With tower beating, Anselm opened final chest: three dials. "Sum of three digits is 27. Only one combination opens: the jewel of Nebelheim".', puzzle: PuzzleModel(id:'B30', title:'Puzzle 30: The Jewel of Nebelheim', statement:'Look at 3 dials (0-9). Sum of 3 digits is 27. Only one combination possible with single digits. What is the key?', experiencia:50, correctAnswer:'999', hintText:'Only digit that summed 3 times is 9.', hints:['9+9+9=27.','999.','Answer 999.'], type:PuzzleType.visualChoice, options:['999','899','992','789'], visualKind:'dials', visualPayload:'3-dials-sum-27')),
];

// Helper maps for other books EN story texts (concise translations)
const enLighthouseMeta = {'title':'The Lighthouse of Lost Tides','subtitle':'Stage 2 · Coastal Mystery','description':'Marealta lighthouse is dark and the keeper vanished. Smuggling, tides and a light that must return.'};
const enCarnivalMeta = {'title':'The Carnival of Masks','subtitle':'Stage 3 · Theft in Belmaro','description':'The Gold Mask vanished at carnival and the thief leaves only riddles. Confetti, costumes and a midnight finale.'};
const enObservatoryMeta = {'title':'The Observatory Star','subtitle':'Stage 4 · Final: Comet Night','description':'Blue Comet returns after a hundred years, but the lens is stolen. Stars, domes and a sky that cannot wait.'};
const enTrainMeta = {'title':'The Midnight Express Mystery','subtitle':'Stage 5 · A Passenger Vanished','description':'A banker vanishes from a locked moving compartment. Fifteen pages of tunnels, snow and a hidden ruby.'};
const enAbbeyMeta = {'title':'The Abbey of Whispers','subtitle':'Stage 6 · The Missing Reliquary','description':'A whispering gallery and a stolen reliquary among ancient walls. Fifteen pages of fog, monks and dawn.'};

// Inline visual puzzles EN (F05, C05, O05/O09/O10, T08/T13, A06/A11)
const PuzzleModel f05En = PuzzleModel(id:'F05', title:'Puzzle 5: The Odd Shell', statement:'Look at the 4 figures of the mosaic. Three are equal and one is different. Which is the odd figure? Write it.', experiencia:25, correctAnswer:'▲', hintText:'Compare one by one: circle, circle… and the third?', hints:['Compare each.','One is triangle.','Answer ▲.'], type:PuzzleType.visualChoice, options:['●','▲','■','★'], visualKind:'odd_one_out', visualPayload:'●,●,▲,●');
const PuzzleModel c05En = PuzzleModel(id:'C05', title:'Puzzle 5: Triangles in the Window', statement:'Look: two triangles sharing one side. How many triangles in total in the figure?', experiencia:20, correctAnswer:'2', hintText:'They share a side but remain two triangles.', hints:['Share one.','Still two.','Answer 2.'], type:PuzzleType.visualChoice, options:['1','2','3','5'], visualKind:'matchsticks', visualPayload:'2-triangles-share-side');
const PuzzleModel o05En = PuzzleModel(id:'O05', title:'Puzzle 5: Meteorites in Balance', statement:'Look: one side has 2x5kg and 2x1kg. How many 3kg weights need on other side to balance?', experiencia:25, correctAnswer:'4', hintText:'Other side 2*5+2*1=12kg.', hints:['12kg.','12/3=4.','Answer 4.'], type:PuzzleType.visualChoice, options:['3','4','5','6'], visualKind:'balance', visualPayload:'2×5kg + 2×1kg|? × 3kg');
const PuzzleModel o09En = PuzzleModel(id:'O09', title:'Puzzle 9: The Night Frieze', statement:'Look at sequence: ★ ● ★ ● ★ … What figure must be sixth to complete pattern?', experiencia:25, correctAnswer:'●', hintText:'Pattern alternates star and circle: ★ ● ★ ●…', hints:['Alternate.','Sixth is ●.','Answer ●.'], type:PuzzleType.visualChoice, options:['★','●','■','▲'], visualKind:'shapes_sequence', visualPayload:'★,●,★,●,★,?');
const PuzzleModel o10En = PuzzleModel(id:'O10', title:'Puzzle 10: The Full Firmament', statement:'Look at 4x4 floor grid. How many squares of all sizes total (1x1,2x2,3x3,4x4)?', experiencia:50, correctAnswer:'30', hintText:'Sum 16+9+4+1.', hints:['30.','Count all.','30.'], type:PuzzleType.visualChoice, options:['16','24','29','30'], visualKind:'grid_squares', visualPayload:'4x4');
const PuzzleModel t08En = PuzzleModel(id:'T08', title:'Puzzle 8: The Banker Ruby', statement:'Red chest: "Ruby is in blue". Blue chest: "Ruby is here". Green chest: "Ruby is not here". Only ONE statement is true. Where is the ruby? Choose color.', experiencia:40, correctAnswer:'red', hintText:'Assume only red tells truth.', hints:['Test red true.','Answer red.','Red.'], type:PuzzleType.visualChoice, options:['red','blue','green'], visualKind:'chests', visualPayload:'red,blue,green');
const PuzzleModel t13En = PuzzleModel(id:'T13', title:'Puzzle 13: The Small Mosaic', statement:'Look at 2x2 floor grid. How many squares of all sizes total (1x1 and 2x2)?', experiencia:25, correctAnswer:'5', hintText:'4+1.', hints:['5.','4+1.','5.'], type:PuzzleType.visualChoice, options:['4','5','6','9'], visualKind:'grid_squares', visualPayload:'2x2');
const PuzzleModel a06En = PuzzleModel(id:'A06', title:'Puzzle 6: The Odd Stained Glass', statement:'Look at 4 figures of the rose window. Three are equal and one is different. Which is the odd figure? Write it.', experiencia:25, correctAnswer:'★', hintText:'Compare: square, square… and third?', hints:['One star.','Answer ★.','★.'], type:PuzzleType.visualChoice, options:['●','▲','■','★'], visualKind:'odd_one_out', visualPayload:'■,■,★,■');
const PuzzleModel a11En = PuzzleModel(id:'A11', title:'Puzzle 11: The Inverted Pyramid', statement:'Look at 10-coin pyramid (rows 1,2,3,4). How many coins must you move minimum to make pyramid point down?', experiencia:35, correctAnswer:'3', hintText:'Three corner coins move.', hints:['3 corners.','Answer 3.','3.'], type:PuzzleType.visualChoice, options:['1','2','3','4'], visualKind:'coin_triangle', visualPayload:'10-coins-invert');
